WITH C AS (SELECT A.BOOK_ID, A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.PRICE
           FROM BOOK AS A
           INNER JOIN AUTHOR AS B ON A.AUTHOR_ID = B.AUTHOR_ID
), D AS (SELECT BOOK_ID, SALES_DATE, SUM(SALES) AS SALES
         FROM BOOK_SALES
         WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=1
         GROUP BY BOOK_ID
)
SELECT C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY, SUM(C.PRICE*D.SALES) AS TOTAL_SALES
FROM C
INNER JOIN D ON C.BOOK_ID=D.BOOK_ID
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME, C.CATEGORY
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC