WITH A AS (SELECT CART_ID, NAME
           FROM CART_PRODUCTS
           WHERE NAME='Milk'
           GROUP BY CART_ID
           UNION ALL
           SELECT CART_ID, NAME
           FROM CART_PRODUCTS
           WHERE NAME='Yogurt'
           GROUP BY CART_ID
)

SELECT CART_ID
FROM A
GROUP BY CART_ID
HAVING COUNT(CART_ID)>1
ORDER BY CART_ID