SELECT PARENT.ID, COUNT(CHILD.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS PARENT
LEFT OUTER JOIN ECOLI_DATA AS CHILD ON PARENT.ID=CHILD.PARENT_ID
GROUP BY PARENT.ID
ORDER BY PARENT.ID
-- OUTER JOIN 사용해야 자식이 없는 경우까지 포함됨