-- NTILE 함수 : 행 데이터를 그룹별로 나누어 차례대로 행 번호를 부여
SELECT ID, (CASE
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY)=1 THEN 'LOW'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY)=2 THEN 'MEDIUM'
            WHEN NTILE(4) OVER (ORDER BY SIZE_OF_COLONY)=3 THEN 'HIGH'
            ELSE 'CRITICAL' END) AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID