WITH A AS (
    SELECT ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANK_NUM, 
           ID, 
           SIZE_OF_COLONY,
           COUNT(*) OVER() AS TOTAL  -- 전체 행 개수를 모든 행에서 동일하게 계산, GROUP BY 필요X
    FROM ECOLI_DATA
)
SELECT E.ID, CASE
            WHEN A.RANK_NUM <= A.TOTAL*0.25 THEN 'CRITICAL'
            WHEN A.RANK_NUM <= A.TOTAL*0.5 THEN 'HIGH'
            WHEN A.RANK_NUM <= A.TOTAL*0.75 THEN 'MEDIUM'
            ELSE 'LOW' END AS COLONY_NAME
FROM ECOLI_DATA AS E
JOIN A ON E.ID=A.ID
ORDER BY ID