-- CHANGE_DATE <= 2019-08-16인 가격 변경 내역 중
-- 각 PRODUCT_ID별 최신 날짜의 가격 찾기
-- 해당 날짜에 변경 이력이 없으면 10
WITH LATEST_PRICE AS (
    SELECT PRODUCT_ID, NEW_PRICE, ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY CHANGE_DATE DESC) AS RNK
    FROM PRODUCTS
    WHERE CHANGE_DATE <= '2019-08-16'
),
ALL_PRODUCT AS (
    SELECT DISTINCT PRODUCT_ID FROM PRODUCTS
)
SELECT P.PRODUCT_ID, IFNULL(L.NEW_PRICE,10) AS PRICE
FROM ALL_PRODUCT P
LEFT JOIN LATEST_PRICE L ON P.PRODUCT_ID=L.PRODUCT_ID AND L.RNK=1