-- 2021년 가입한 전체 회원 수
WITH A AS (SELECT USER_ID, (SELECT COUNT(*) 
                            FROM USER_INFO 
                            WHERE JOINED LIKE '2021%') AS TOTAL
           FROM USER_INFO
           WHERE JOINED LIKE '2021%'
           )

SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT B.USER_ID)/A.TOTAL,1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS B
JOIN A ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH