-- 2021년 가입한 전체 회원의 ID : JOIN할 때 필요
WITH A AS (SELECT USER_ID
           FROM USER_INFO
           WHERE JOINED LIKE '2021%'),

-- 2021년 가입한 전체 회원 수 : 나눌 때 필요
B AS (SELECT COUNT(*) AS TOTAL
      FROM A)

SELECT YEAR(C.SALES_DATE) AS YEAR, 
        MONTH(C.SALES_DATE) AS MONTH,
        COUNT(DISTINCT C.USER_ID) AS PURCHASED_USERS,
        ROUND(COUNT(DISTINCT C.USER_ID)/B.TOTAL, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS C
JOIN A ON A.USER_ID = C.USER_ID
JOIN B
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH