-- 세대 구하는 쿼리
-- WITH RECURSIVE : 테이블 자신의 값을 참조
WITH RECURSIVE GENERATION AS(
    -- 1세대
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    -- 자식 세대 = 부모 세대 +1
    SELECT E.ID, G.GENERATION+1
    FROM ECOLI_DATA AS E
    JOIN GENERATION AS G ON E.PARENT_ID=G.ID
),
-- 자식이 없는 개체만 추출 : 반드시 LEFT JOIN
A AS (
    SELECT G.ID, G.GENERATION
    FROM GENERATION AS G
    LEFT JOIN ECOLI_DATA AS C ON G.ID=C.PARENT_ID
    WHERE C.ID IS NULL
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM A
GROUP BY GENERATION
ORDER BY GENERATION