#재귀 쿼리 : CTE
WITH RECURSIVE CTE AS (
    -- 1세대 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    -- 두개의 쿼리 결과 합침 (중복 행 포함)
    UNION ALL
    -- 자식 개체에 대해 세대 계산 (+1)
    SELECT E.ID, E.PARENT_ID, CTE.GENERATION+1
    FROM ECOLI_DATA E
    JOIN CTE ON E.PARENT_ID = CTE.ID
)

SELECT COUNT(A.ID) AS COUNT, A.GENERATION
FROM CTE as A
LEFT JOIN CTE B ON A.ID = B.PARENT_ID
WHERE B.ID IS NULL
GROUP BY A.GENERATION