-- 자동차 종류가 '트럭'인 자동차의 대여 기록에 대한 대여 기간
WITH T AS (SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DAY,
           CASE
           WHEN DATEDIFF(END_DATE, START_DATE)+1>=90 THEN '90일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE)+1>=30 THEN '30일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE)+1>=7 THEN '7일 이상'
           ELSE '할인없음' END AS DURATION_TYPE
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
),
D AS (SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
      WHERE CAR_TYPE = '트럭' 
)
SELECT T.HISTORY_ID, 
    CASE
    WHEN T.DURATION_TYPE = '할인없음' THEN ROUND(C.DAILY_FEE*T.DAY,0)
    ELSE ROUND(C.DAILY_FEE*(1-0.01*D.DISCOUNT_RATE)*T.DAY,0) 
    END AS FEE
FROM T
LEFT JOIN D ON T.DURATION_TYPE=D.DURATION_TYPE
LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C ON T.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE='트럭'
ORDER BY FEE DESC, T.HISTORY_ID DESC