WITH PATIENT_TABLE AS (
    SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MDDR_ID, A.MCDP_CD, A.APNT_YMD
    FROM APPOINTMENT AS A
    INNER JOIN PATIENT AS B ON A.PT_NO=B.PT_NO
    WHERE A.APNT_YMD LIKE '2022-04-13%' AND A.APNT_CNCL_YN = 'N')

SELECT A.APNT_NO, A.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM PATIENT_TABLE AS A
INNER JOIN DOCTOR AS B ON A.MCDP_CD=B.MCDP_CD AND A.MDDR_ID=B.DR_ID
ORDER BY A.APNT_YMD