-- 연간 평가점수를 구해야 함 : 반기 합(1+2) 평균
WITH T AS (SELECT EMP_NO, SUM(SCORE)/2 AS SCORE
           FROM HR_GRADE
           GROUP BY EMP_NO
)
SELECT H.EMP_NO, H.EMP_NAME,
CASE
    WHEN T.SCORE >= 96 THEN 'S'
    WHEN T.SCORE >= 90 THEN 'A'
    WHEN T.SCORE >= 80 THEN 'B'
    ELSE 'C' END AS GRADE,
CASE 
    WHEN T.SCORE >= 96 THEN H.SAL*0.2
    WHEN T.SCORE >= 90 THEN H.SAL*0.15
    WHEN T.SCORE >= 80 THEN H.SAL*0.1
    ELSE H.SAL*0 END AS BONUS
FROM HR_EMPLOYEES AS H
JOIN T ON T.EMP_NO=H.EMP_NO