-- 최대 리뷰 회원 조회
WITH T AS (SELECT MEMBER_ID, COUNT(*)
           FROM REST_REVIEW
           GROUP BY MEMBER_ID
           ORDER BY COUNT(*) DESC LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM T
JOIN REST_REVIEW AS A ON T.MEMBER_ID=A.MEMBER_ID
LEFT JOIN MEMBER_PROFILE AS B ON T.MEMBER_ID=B.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT