-- Python 또는 C# 스킬을 가진 개발자
-- 비트연산자 : 개별 스킬로 세분화 필요
/*
SELECT * 
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S ON S.CODE & D.SKILL_CODE = S.CODE
*/
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S ON S.CODE & D.SKILL_CODE = S.CODE
WHERE S.NAME LIKE 'Python%' OR S.NAME LIKE 'C#%'
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY D.ID