WITH A AS (SELECT MAX(SIZE_OF_COLONY) AS MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
           FROM ECOLI_DATA
           GROUP BY YEAR(DIFFERENTIATION_DATE)
)
-- YEAR가 같도록 조인해야함
SELECT A.YEAR, A.MAX-E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN A ON YEAR(E.DIFFERENTIATION_DATE) = A.YEAR
ORDER BY A.YEAR, YEAR_DEV