SELECT A.TITLE, B.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A, USED_GOODS_REPLY AS B
WHERE A.BOARD_ID = B.BOARD_ID AND EXTRACT(YEAR FROM A.CREATED_DATE) = 2022 AND EXTRACT(MONTH FROM A.CREATED_DATE) = 10
ORDER BY CREATED_DATE, TITLE