-- 각 행의 사람 수가 100명 이상인 연속된 ID가 3개 이상 있는 레코드
-- 출력되는 ID가 연속된 3개 이상인지 확인해야함
WITH A AS (
    SELECT ROW_NUMBER() OVER(ORDER BY ID) AS NUM, ID, PEOPLE
    FROM STADIUM
    WHERE PEOPLE >= 100
),
B AS (
    SELECT ID, ID-NUM AS DIFF, COUNT(ID) OVER(PARTITION BY ID-NUM) AS CNT
    FROM A
    GROUP BY ID, DIFF
)
SELECT S.ID, S.VISIT_DATE, S.PEOPLE
FROM STADIUM S
JOIN B ON S.ID=B.ID
WHERE CNT >= 3