-- 비트연산자
-- A는 Pyhton & Front End 외 다른 스킬 가질 수 있음을 유의 ex. 400 = 256+128+16
-- 아래 코드 실행해보면, SKILL_CODE가 세분화되어 출력됨
/*
SELECT *
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S ON (D.SKILL_CODE & S.CODE = S.CODE)
*/
-- GROUP_CONCAT 사용해서 케이스 분류 후, 출력
SELECT
    CASE 
    WHEN GROUP_CONCAT(S.NAME) LIKE '%Python%' AND GROUP_CONCAT(S.CATEGORY) LIKE '%Front%' THEN 'A'
    WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN 'B'
    WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front%' THEN 'C'
    END AS GRADE, D.ID, D.EMAIL
FROM DEVELOPERS AS D
JOIN SKILLCODES AS S ON (D.SKILL_CODE & S.CODE = S.CODE)
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID
